- added statistics gathering for 3 paths - optimized setup/teardown time for experiments (omp parallel stat clearing / init) - cleaned up statistics gathering for hytm2 (it should be good now) - cleaned up build system slightly (ignore build.inc_old.sh. now we simply use dsbench/scripts/compile_x64.sh for x86/64 stuff) - added proper thread pinning for zyra (144 thread machine) - added parallel data processing after long runs - cleaned up code rot in experimental scripts for x86/64 (see dsbench/scripts/dsbench and dsbench.format.parallel - ran some basic data (mimicking the experimental setup in the paper) on zyra (144 thread system) ... seems like hardware tm based algorithms take some big perf hit in the 100% search workload... need more statistics gathering on cache misses etc. (will instrument with PAPI next)

diff --git a/code/stamp/dsbench/scripts/dsbench b/code/stamp/dsbench/scripts/dsbench
--- a/code/stamp/dsbench/scripts/dsbench
+++ b/code/stamp/dsbench/scripts/dsbench
@@ -7,17 +7,17 @@ expname=dsbench
 seqwidth=48
 
 algs_reclaimers_pools="dsbench_tl2~debra~none dsbench_hytm1~debra~none dsbench_hytm2~debra~none dsbench_hytm3~debra~none dsbench_hybridnorec~debra~none"
-algs_reclaimers_pools="$algs_reclaimers_pools dsbench_tl2~none~none dsbench_hytm1~none~none dsbench_hytm2~none~none dsbench_hytm3~none~none dsbench_hybridnorec~none~none"
+#algs_reclaimers_pools="$algs_reclaimers_pools dsbench_tl2~none~none dsbench_hytm1~none~none dsbench_hytm2~none~none dsbench_hytm3~none~none dsbench_hybridnorec~none~none"
 
 if [ "$machine" == "cheshire-r07u03" ]; then
     algs_reclaimers_pools="$algs_reclaimers_pools dsbench_hytm2_nonspec~debra~none dsbench_hybridnorec_nonspec~debra~none"
-    algs_reclaimers_pools="$algs_reclaimers_pools dsbench_hytm2_nonspec~none~none dsbench_hybridnorec_nonspec~none~none"
+    #algs_reclaimers_pools="$algs_reclaimers_pools dsbench_hytm2_nonspec~none~none dsbench_hybridnorec_nonspec~none~none"
 fi
 
-keyranges="10000"
-insdel_pcnts="0 1 5"
+keyranges="10000 100000"
+insdel_pcnts="0 1 5 20"
 
-ntrials=6
+ntrials=20
 t=1000
 timeoutsec=`expr $t / 1000`
 timeoutsec=`expr $timeoutsec + 3`
@@ -33,11 +33,15 @@ if [ "$#" -ne "0" ]; then
 	p=
 fi
 
+##########################################################
+## NOTE DIRECTORY CHANGE!
+##########################################################
 cd ..
+# we are now running in ../
 
-# assuming we are running in ../
 outdir=output.${machine}.${expname}
-libdir=../lib/x32
+libdir=../lib
+bindir=.
 scriptsdir=scripts
 logfile=$outdir/log.out
 compilinglogfile=$outdir/compiling.out
@@ -45,21 +49,22 @@ stderrfile=$outdir/stderr.out
 f=$outdir/temp.out
 
 # back up old output dir, and create a new one
-rm -r -f $outdir.old
-mv $outdir $outdir.old
-mkdir $outdir
+rm -r -f $outdir.old 2>/dev/null
+mv $outdir $outdir.old 2>/dev/null
+mkdir $outdir 2>/dev/null
 
 envcmd=""
 
-## locate jemalloc library
-#if [ -e "${libdir}/libjemalloc.so" ]; then
-#    envcmd="env LD_PRELOAD=${libdir}/libjemalloc.so"
-##elif [ -e "${libdir}/libjemalloc.so" ]; then
-##    envcmd="env LD_PRELOAD=${libdir}/libjemalloc.so.2"
-#else
-#    echo "ERROR: could not find jemalloc library"
-#    exit 1
-#fi
+# locate jemalloc library
+if [ -e "${libdir}/libjemalloc.so" ]; then
+    envcmd="LD_PRELOAD=${libdir}/libjemalloc.so"
+elif [ -e "${libdir}/libjemalloc.so.2" ]; then
+    envcmd="LD_PRELOAD=${libdir}/libjemalloc.so.2"
+else
+    echo "envcmd=$envcmd libdir=$libdir ifexists=${libdir}/libjemalloc.so.2"
+    echo "ERROR: could not find jemalloc library"
+    exit 1
+fi
 
 echo "-------------------- BEGIN VARIABLES --------------------" >> $logfile
 ( set -o posix ; set ) >> $logfile
@@ -68,9 +73,11 @@ echo "--------------------- END VARIABLES ---------------------" >> $logfile
 cat $logfile
 
 ### COMPILE ALL ALGORITHMS
-make -f Makefile.stm -j machine=`hostname` EXTRAFLAGS3=-DHTM_ATTEMPT_THRESH=20 pinning=$pinnings
+#echo "!!!!!!!!!!!! pinnings=$pinnings"
+bash -c "cd scripts ; ./compile_x64.sh \"$pinnings\""
+#make -f Makefile.stm -j machine=`hostname` EXTRAFLAGS3=-DHTM_ATTEMPT_THRESH=20 pinning=$pinnings
 
-problems=""
+#problems=""
 
 cnt1=0
 cnt2=0
@@ -123,12 +130,12 @@ for pinning in $pinnings; do
                         fname="$outdir/$fname.data"
                         ############# ADD BINDING ARGUMENT TO COMMAND AFTER CREATING THE FILENAME
                         #cmd="$cmd $bindingarg"
-                        echo "timeout $timeoutsec $envcmd ${malloc_conf} $cmdprefix ./$cmd > $fname"
-                        echo "timeout $timeoutsec $envcmd ${malloc_conf} $cmdprefix ./$cmd" > $fname
-                        timeout $timeoutsec $envcmd ${malloc_conf} $cmdprefix ./$cmd >> $fname 2>>$stderrfile
+                        echo "$envcmd ${malloc_conf} timeout $timeoutsec $cmdprefix $bindir/$cmd >> $fname 2>>$stderrfile"
+                        echo "$envcmd ${malloc_conf} timeout $timeoutsec $cmdprefix $bindir/$cmd >> $fname 2>>$stderrfile" > $fname
+                        eval "$envcmd ${malloc_conf} timeout $timeoutsec $cmdprefix $bindir/$cmd >> $fname 2>>$stderrfile"
                         if [ "$?" -ne "0" ]; then
-                            problems="${problems}ERROR: nonzero status after executing cmd ``timeout $timeoutsec $envcmd ${malloc_conf} $cmdprefix ./$cmd >> $fname\n''"
-                            echo "ERROR: nonzero status after executing cmd"
+                            #problems="${problems}ERROR: nonzero status after executing cmd ``$envcmd ${malloc_conf} timeout $timeoutsec $cmdprefix $bindir/$cmd >> $fname 2>>$stderrfile\n''"
+                            echo "ERROR: nonzero status after executing preceding command"
                             #cat $stderrfile
                             #exit
                         fi
@@ -152,5 +159,5 @@ rm -f $compilinglogfile
 #./${expname}.format ${machine}
 #cd ..
 
-echo -e $problems
+#echo -e $problems
 cat $stderrfile
