Lots of changes. Crucially, fixed huge scaling/performance problems for almost all TM algorithms. We now directly include the TM library so calls can be inlined. Switched from if(Self->isFallback) in TxLoad and TxStore to function pointers that change targets when a TM changes paths. Fixed a bug in build_x86 that prevented the -mx32 argument from being passed to the compiler. Added a rangeIncrement operation to the BST and the dsbench scripts. Fixed a false sharing bug in hybrid norec. Fixed two hash table expansion bugs in hytm1/2/3/hybridnorec. Removed extraneous thread pinning in thread.c. Added spreadsheet for formatting data into graphs. (The data it contains is invalid.)

diff --git a/code/stamp/dsbench/scripts/dsbench b/code/stamp/dsbench/scripts/dsbench
--- a/code/stamp/dsbench/scripts/dsbench
+++ b/code/stamp/dsbench/scripts/dsbench
@@ -6,13 +6,14 @@ expname=dsbench
 
 seqwidth=48
 algs_reclaimers_pools="dsbench_tl2~debra~none dsbench_hytm1~debra~none dsbench_hytm2~debra~none dsbench_hytm3~debra~none dsbench_hybridnorec~debra~none"
-keyranges="1000 10000 100000"
-insdel_pcnts="5 10 50"
-ntrials=8
+keyranges="100000"
+insdel_pcnts="0 5 20 50"
+
+ntrials=6
 t=1000
 p=-p
 ma=new
-pinnings="${pin_cluster} ${pin_scatter}"
+pinnings="${pin_cluster}"
 
 if [ "$#" -ne "0" ]; then
 	echo "RUNNING IN TEST MODE"
@@ -37,15 +38,17 @@ rm -r -f $outdir.old
 mv $outdir $outdir.old
 mkdir $outdir
 
-# locate jemalloc library
-if [ -e "${libdir}/libjemalloc.so" ]; then
-    envcmd="env LD_PRELOAD=${libdir}/libjemalloc.so"
-#elif [ -e "${libdir}/libjemalloc.so" ]; then
-#    envcmd="env LD_PRELOAD=${libdir}/libjemalloc.so.2"
-else
-    echo "ERROR: could not find jemalloc library"
-    exit 1
-fi
+envcmd=""
+
+## locate jemalloc library
+#if [ -e "${libdir}/libjemalloc.so" ]; then
+#    envcmd="env LD_PRELOAD=${libdir}/libjemalloc.so"
+##elif [ -e "${libdir}/libjemalloc.so" ]; then
+##    envcmd="env LD_PRELOAD=${libdir}/libjemalloc.so.2"
+#else
+#    echo "ERROR: could not find jemalloc library"
+#    exit 1
+#fi
 
 echo "-------------------- BEGIN VARIABLES --------------------" >> $logfile
 ( set -o posix ; set ) >> $logfile
@@ -78,29 +81,39 @@ for counting in 1 0; do
 
             for insdel_pcnt in $insdel_pcnts; do
             for nthreads in $threadcounts; do
-            for ((trial=0;trial<$ntrials;++trial)); do
-                if [ $counting -eq 1 ]; then
-                    cnt1=`expr $cnt1 + 1`
-                    continue
+                if [ "$nthreads" -gt "1" ]; then
+                    nminusone=`expr $nthreads - 1`
+                    workandrqcounts="${nthreads}~0 ${nminusone}~1"
+                else
+                    workandrqcounts="${nthreads}~0"
                 fi
+                for nworkandrq in $workandrqcounts; do
+                    nwork=`echo $nworkandrq | cut -d"~" -f1`
+                    nrq=`echo $nworkandrq | cut -d"~" -f2`
+                    for ((trial=0;trial<$ntrials;++trial)); do
+                        if [ $counting -eq 1 ]; then
+                            cnt1=`expr $cnt1 + 1`
+                            continue
+                        fi
 
-                cnt2=`expr $cnt2 + 1`
-                echo -n "trial $cnt2 / $cnt1: "
+                        cnt2=`expr $cnt2 + 1`
+                        echo -n "trial $cnt2 / $cnt1: "
 
-                args="-t $t -mr $mr -ma $ma -mp $mp $p -k $k -i $insdel_pcnt -d $insdel_pcnt -rq 0 -nwork $nthreads"
-                cmd="$machine.$alg $args"
-                fname=`echo $cmd | tr " " "."`
-                fname="step$cnt2.${fname}.-seqwidth.$seqwidth.-trial.$trial"
-                fname="$outdir/$fname.data"
-                echo "$envcmd ${malloc_conf} $cmdprefix ./$cmd > $fname"
-                echo "$envcmd ${malloc_conf} $cmdprefix ./$cmd" > $fname
-                $envcmd ${malloc_conf} $cmdprefix ./$cmd >> $fname 2>>$stderrfile
-                if [ "$?" -ne "0" ]; then
-                    echo "ERROR: nonzero status after executing cmd"
-                    cat $stderrfile
-                    exit
-                fi
-            done
+                        args="-t $t -mr $mr -ma $ma -mp $mp $p -k $k -i $insdel_pcnt -d $insdel_pcnt -rq 0 -rqsize 256 -nwork $nwork -nrq $nrq"
+                        cmd="$machine.$alg $args"
+                        fname=`echo $cmd | tr " " "."`
+                        fname="step$cnt2.${fname}.-seqwidth.$seqwidth.-trial.$trial"
+                        fname="$outdir/$fname.data"
+                        echo "$envcmd ${malloc_conf} $cmdprefix ./$cmd > $fname"
+                        echo "$envcmd ${malloc_conf} $cmdprefix ./$cmd" > $fname
+                        $envcmd ${malloc_conf} $cmdprefix ./$cmd >> $fname 2>>$stderrfile
+                        if [ "$?" -ne "0" ]; then
+                            echo "ERROR: nonzero status after executing cmd"
+                            cat $stderrfile
+                            exit
+                        fi
+                    done
+                done
             done
         done
     done
